//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/NewControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NewControls"",
    ""maps"": [
        {
            ""name"": ""WeaponWheelMap"",
            ""id"": ""7aaf2217-1350-45a8-954f-4591024d0546"",
            ""actions"": [
                {
                    ""name"": ""OpenWeaponWheel"",
                    ""type"": ""Button"",
                    ""id"": ""b2ad8f6f-dd02-4df1-b05a-6a5a4c1d9d6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a41e78f5-3278-4ec6-a98d-16e99b923d21"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenWeaponWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // WeaponWheelMap
        m_WeaponWheelMap = asset.FindActionMap("WeaponWheelMap", throwIfNotFound: true);
        m_WeaponWheelMap_OpenWeaponWheel = m_WeaponWheelMap.FindAction("OpenWeaponWheel", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // WeaponWheelMap
    private readonly InputActionMap m_WeaponWheelMap;
    private IWeaponWheelMapActions m_WeaponWheelMapActionsCallbackInterface;
    private readonly InputAction m_WeaponWheelMap_OpenWeaponWheel;
    public struct WeaponWheelMapActions
    {
        private @NewControls m_Wrapper;
        public WeaponWheelMapActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenWeaponWheel => m_Wrapper.m_WeaponWheelMap_OpenWeaponWheel;
        public InputActionMap Get() { return m_Wrapper.m_WeaponWheelMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WeaponWheelMapActions set) { return set.Get(); }
        public void SetCallbacks(IWeaponWheelMapActions instance)
        {
            if (m_Wrapper.m_WeaponWheelMapActionsCallbackInterface != null)
            {
                @OpenWeaponWheel.started -= m_Wrapper.m_WeaponWheelMapActionsCallbackInterface.OnOpenWeaponWheel;
                @OpenWeaponWheel.performed -= m_Wrapper.m_WeaponWheelMapActionsCallbackInterface.OnOpenWeaponWheel;
                @OpenWeaponWheel.canceled -= m_Wrapper.m_WeaponWheelMapActionsCallbackInterface.OnOpenWeaponWheel;
            }
            m_Wrapper.m_WeaponWheelMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OpenWeaponWheel.started += instance.OnOpenWeaponWheel;
                @OpenWeaponWheel.performed += instance.OnOpenWeaponWheel;
                @OpenWeaponWheel.canceled += instance.OnOpenWeaponWheel;
            }
        }
    }
    public WeaponWheelMapActions @WeaponWheelMap => new WeaponWheelMapActions(this);
    public interface IWeaponWheelMapActions
    {
        void OnOpenWeaponWheel(InputAction.CallbackContext context);
    }
}
